### ISSUE TITLE
How we can disable time as well in Datetime picker

### ISSUE THREAD

**Issue by ParthWeb** [LibusoftCicom/lc-datepicker#10]
Is there any way if we can disable time in datetime picker, for specific hours

**Comment by mematija** [comment]
Hi Parth,

currently this is not possible. We probably will add this feature, but haven't yet decided on exact timeline - but it could be by the end of the month ;)

**Comment by ParthWeb** [comment]
@mematija  ok thank you madam..looking forward to this

**Comment by mematija** [comment]
Closed with commit 9b11c562a7a975d75f01e8305f29670181b6aab4.
