### ISSUE TITLE
Remove disabled years from the list

### ISSUE THREAD

**Issue by WeekendMan** [LibusoftCicom/lc-datepicker#11]
If I created config like

```
const config: DatePickerConfig = new DatePickerConfig();
config.CalendarType = ECalendarType.Date;
config.MinDate = { years: 1986, months: 1, date: 1 };
config.MaxDate = { years: 1987, months: 12, date: 31 };
```

it's totally unclear that all years from the 0 (and even -100500th year is still available) and till the 1000000000 are available in the year list. Also, this scroll is too hard for the touchpad on the laptop. Can you show only allowed years in the year list?

**Comment by mematija** [comment]
Hi @WeekendMan,
this will be implemented in upcoming release.

Thank you for your feedback!
