### ISSUE TITLE
Enable the disabled timerange

### ISSUE THREAD

**Issue by NaseerDragonRose** [LibusoftCicom/lc-datepicker#12]
I'm facing an issue where I have a **start date-time** and **end date-time**, where startDate should always be **1 minute** less than endDate.

I have written a condition to add disable time range as below:
```
setEndDateOptions() {
    const today = moment().format();
    let startDate = this.startDateTime;
    this.endDateTimeConfig.MinDate = {
        date: moment(today).get('date'),
        months: moment(today).get('month'),
        years: moment(today).get('year')
    };
    if (startDate) {
        if (startDate.substring(0, 10) === today.substring(0, 10)) {
            const minTime = startDate.split('T')[1];
            this.endDateTimeConfig.addDisabledTimeRange('00:00', minTime);
        }
    }
}
```

So as per above code when startDate and endDate are same and if startDate is selected, disable all the time range from 00:00 till startTime. But if I go back and change the startDate to a previous date still the disabled time range is disabled.

I tried the below code which is throwing error:
```
// Cannot assign to 'DisabledTimeRanges' because it is a read-only property.
this.endDateTimeConfig.DisabledTimeRanges = [];
```

Please let me know how I can enable the disabled timerange.

**Comment by nradanovic** [comment]
Hi @NaseerDragonRose ,

we added clearDisabledTimeRange function which clears disabled timeranges.
