### ISSUE TITLE
Not compiling with angular version 4

### ISSUE THREAD

**Issue by ZikZakJainy** [LibusoftCicom/lc-datepicker#13]
Error Log : -
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,79): Cannot find name 'T'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,44): ';' expected.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,77): Expression expected.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,52): ';' expected.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,88): ';' expected.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,92): Expression expected.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,52): 'ObservableInput' only refers to a type, but is being used as a value here.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,68): Cannot find name 'infer'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,74): Cannot find name 'T'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,74): ';' expected.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (81,83): Cannot find name 'never'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,66): 'ObservableInput' only refers to a type, but is being used as a value here.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,82): Cannot find name 'infer'.
ERROR in systemPathnode_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,88): Cannot find name 'T'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,94): Cannot find name 'T'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/types.d.ts (82,98): Cannot find name 'never'.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/Notification.d.ts (7,12): In ambient enum declarations member initializer must be constant expression.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/Notification.d.ts (8,13): In ambient enum declarations member initializer must be constant expression.
ERROR in systemPath/node_modules/@libusoftcicom/lc-datepicker/node_modules/rxjs/internal/Notification.d.ts (9,16): In ambient enum declarations member initializer must be constant expression.

**Comment by ZikZakJainy** [comment]
Using 
    "rxjs": "5.4.3",
    "rxjs-compat": "6.4.0",

**Comment by nradanovic** [comment]
Hi @ZikZakJainy ,
this bug was fixed in latest commit.
