### ISSUE TITLE
Compile error Module not found: Error: Can't resolve 'moment-es6' Angular 8

### ISSUE THREAD

**Issue by Vaibhav2812** [LibusoftCicom/lc-datepicker#14]
package.json: 
"@libusoftcicom/lc-datepicker": "^1.5.2";
"moment": "^2.25.3";

even I used moment 2.24, the same error coming.

**Comment by pIvan** [comment]
Hi @Vaibhav2812,
if you check the library [package.json](https://github.com/LibusoftCicom/lc-datepicker/blob/master/projects/libusoftcicom/lc-datepicker/package.json) you can see how "moment-es6": "1.0.0" is peerDependency, so what you need is to add same as dependency in your project.

Kind regards,
Ivan
