### ISSUE TITLE
Add Calendar Position config

### ISSUE THREAD

**Issue by kevinfaveri** [LibusoftCicom/lc-datepicker#3]
Can you add a element position config? It would be useful since there is situations like this one when it is at the end of a modal:
![modal bug](https://user-images.githubusercontent.com/18222497/31733921-c49f1c12-b41b-11e7-8733-8b332ec24573.PNG)
This could be solved if there was a position config to 'top', per ex.
Thanks in advance.

**Comment by nradanovic** [comment]
Lc-datepicker is absolutly positioned so you can set it's position with css property.
Ex: 

```
lc-datepicker{
    top: -100px;
    left: 200px;
}
```
