### ISSUE TITLE
how to disabled Dates on datepicker  

### ISSUE THREAD

**Issue by sagarloona4180** [LibusoftCicom/lc-datepicker#5]
![image](https://user-images.githubusercontent.com/29095795/33374757-6f39a750-d52d-11e7-914f-0c577381633d.png)

**Comment by nradanovic** [comment]
Currently you can only set min/max date.
We are planing to add option to disable specific date or date range.

**Comment by pIvan** [comment]
We added the option over which is possible to disable date or list of dates. 
Description how to do that is available on demo [page](https://libusoftcicom.github.io/lc-datepicker/) under section **Define allowed/disabled dates**

**Comment by sagarloona4180** [comment]
thanks  Ivan

*With Warm Regards *
*Sagar Kumar*
*Software Developer*
*Intelligaia Technologies Pvt. Ltd <http://intelligaia.com/>*
*Mobile* | *+91-7006397712*
