### ISSUE TITLE
Import of LcDatePickerModule is missing in the doc

### ISSUE THREAD

**Issue by serge-fabiano** [LibusoftCicom/lc-datepicker#6]
Hi,
You missed the import statement to get the LcDatePickerModule.
Regards,
Serge.

**Comment by serge-fabiano** [comment]
After 
  npm install libusoftcicom/lc-datepickera
There is no index file in the node_modules to import the module or components
Have I missed something?

**Comment by pIvan** [comment]
Hi @LucasBrazi06,
we made update in [documentation](https://libusoftcicom.github.io/lc-datepicker/#installation).
Regarding to question about index file in node_modules folder, 
if compiler uses "node" moduleResolution You do not need any aditinal file or configuration.
