### ISSUE TITLE
The retuned date is wrong, when the current month has less days than the date selected.

### ISSUE THREAD

**Issue by gchr** [LibusoftCicom/lc-datepicker#9]
Hi @mematija ! Nice component!

You can reproduce this behavior right on your demo page https://libusoftcicom.github.io/lc-datepicker/

How to reproduce:
The user's **current** month, must be a month with **less** than 31 days. (Now that I'm writing this is April, and April has 30 days)
If you select the date March **31**st in the picker, the date the component selects (and returns) is March **1**st.

How to fix:
In _lc-datepicker.es5.js_ : function _LCDayPickerComponent.prototype.dayClick_
Swap the two lines 
```
date.date(item.date);
date.month(item.months);
```
to be like this:
```
date.month(item.months);
date.date(item.date);
```

**Comment by nradanovic** [comment]
Hi @gchr

thank you for bug report and fix.
